### ISSUE TITLE
sorry, get error in vercel ....ReferenceError XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by ustphyskkc** [snekkenull/Anthropic-Claude-demo#6]
i have readed the closed issue ........mentioned the same error.....and be fixed .

but when i deployed tat Vercel ......i get the same error, .......how to fix it?

**Comment by snekkenull** [comment]
Sorry, can you paste the log?
I also recommend you to use chatchat.

**Comment by erbanku** [comment]
@snekkenull Same here.
```
Anthropic API Error:  ReferenceError: XMLHttpRequest is not defined
    at (entry.mjs:29:9525)
    at (entry.mjs:29:9393)
    at (entry.mjs:33:317)
    at (entry.mjs:29:11148)
    at (entry.mjs:29:10945)
    at (entry.mjs:33:257)
    at (entry.mjs:172:48)
``` 
![image](https://github.com/snekkenull/Anthropic-Claude-demo/assets/79493862/9722d35e-2ee8-445e-92b7-40e57e5564c6)

**Comment by snekkenull** [comment]
Thanks, I will fix it this week

**Comment by snekkenull** [comment]
Update and fix it, test in vercel, now it works.
